# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Feyza Yavuz
tagline:             ''
description:         'Aloha.'
url:                 http://feyzayavuz.github.io
baseurl:             ''

# About/contact
author:
  name:              Feyza
  url:               https://twitter.com/feyzayavuzz
  email:             feyzaayavuz@gmail.com

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
